#import "recorder.h"

static BOOL g_recording = NO;
static NSMutableArray *g_events = nil;
static NSTimeInterval g_start_time = 0;
static dispatch_queue_t g_queue = nil;

static void ensure_queue(void) {
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        g_queue = dispatch_queue_create("io.iosautotool.recorder", DISPATCH_QUEUE_SERIAL);
    });
}

void recorder_start(void) {
    ensure_queue();
    dispatch_sync(g_queue, ^{
        g_events = [NSMutableArray array];
        g_start_time = [NSDate timeIntervalSinceReferenceDate];
        g_recording = YES;
    });
}

BOOL recorder_is_recording(void) {
    ensure_queue();
    __block BOOL r;
    dispatch_sync(g_queue, ^{ r = g_recording; });
    return r;
}

void recorder_clear(void) {
    ensure_queue();
    dispatch_sync(g_queue, ^{
        g_events = nil;
        g_recording = NO;
    });
}

NSArray *recorder_get_events(void) {
    ensure_queue();
    __block NSArray *snap;
    dispatch_sync(g_queue, ^{
        snap = g_events ? [g_events copy] : @[];
    });
    return snap;
}

static void append_event(NSDictionary *ev) {
    ensure_queue();
    dispatch_sync(g_queue, ^{
        if (g_recording && g_events) [g_events addObject:ev];
    });
}

static int now_ms(void) {
    NSTimeInterval delta = [NSDate timeIntervalSinceReferenceDate] - g_start_time;
    return (int)(delta * 1000);
}

void recorder_log_tap(double x, double y) {
    append_event(@{
        @"type": @"tap",
        @"t":    @(now_ms()),
        @"x":    @(x),
        @"y":    @(y),
    });
}

void recorder_log_swipe(double x1, double y1, double x2, double y2) {
    append_event(@{
        @"type": @"swipe",
        @"t":    @(now_ms()),
        @"x1":   @(x1),
        @"y1":   @(y1),
        @"x2":   @(x2),
        @"y2":   @(y2),
    });
}

NSString *recorder_stop_and_codegen(void) {
    ensure_queue();
    __block NSArray *events;
    dispatch_sync(g_queue, ^{
        g_recording = NO;
        events = g_events ? [g_events copy] : @[];
    });

    NSMutableString *code = [NSMutableString stringWithString:@"-- Generated by Macro Recorder\n"];
    int prev_t = 0;
    for (NSUInteger i = 0; i < events.count; i++) {
        NSDictionary *ev = events[i];
        int t = [ev[@"t"] intValue];
        int gap = t - prev_t;
        if (i > 0 && gap > 50) {
            [code appendFormat:@"system.sleep(%d)\n", gap];
        }
        NSString *type = ev[@"type"];
        if ([type isEqualToString:@"tap"]) {
            [code appendFormat:@"touch.tap(%d, %d)\n",
                [ev[@"x"] intValue], [ev[@"y"] intValue]];
        } else if ([type isEqualToString:@"swipe"]) {
            [code appendFormat:@"touch.swipe(%d, %d, %d, %d, 300)\n",
                [ev[@"x1"] intValue], [ev[@"y1"] intValue],
                [ev[@"x2"] intValue], [ev[@"y2"] intValue]];
        }
        prev_t = t;
    }
    if (events.count == 0) {
        [code appendString:@"-- No events recorded\n"];
    }
    return code;
}
